const $ = (s) => document.querySelector(s);
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusText = {healthy:'정상', degraded:'주의', down:'장애', unknown:'확인 필요', planned:'구축 예정'};
const statusClass = (s) => ({healthy:'ok', degraded:'warn', down:'down', unknown:'unknown', planned:'planned'}[s] || 'unknown');
const ruleGroups = {work_principles:'공통 작업 원칙', release_operations:'승인 · 배포 · 운영 검증', project_operations:'프로젝트별 운영'};
const ruleScopes = {common:'공통', ai_one_plate:'AI 한 접시'};
let services = [];
let ideas = [];
let ga4 = {status:'not_configured'};
let rulesDocument = null;
let activeFilter = 'all';
let activeView = 'overview';
let refreshTimer;
function fmtDate(value) { if (!value) return '기록 없음'; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : d.toLocaleString('ko-KR', {dateStyle:'medium', timeStyle:'short'}); }
function checkSummary(service) { const checks = service.checks || []; if (!checks.length) return '자동 점검 없음'; return checks.map(c => `${esc(c.name)}: ${esc(statusText[c.status] || c.status)}`).join(' · '); }
function renderSummary() { const operating = services.filter(s => s.lifecycle === 'operating'); const healthy = operating.filter(s => s.automated_status === 'healthy').length; const attention = services.filter(s => ['down','degraded','unknown'].includes(s.automated_status)).length; $('#summary').innerHTML = `<div class="stat"><small>운영 서비스</small><b>${operating.length}</b><span>${healthy}/${operating.length} 정상</span></div><div class="stat"><small>확인 필요</small><b class="${attention ? 'warn' : 'ok'}">${attention}</b><span>자동 상태 기준</span></div><div class="stat"><small>예정 서비스</small><b>${services.filter(s => s.lifecycle === 'planned').length}</b><span>범위 결정 대기</span></div><div class="stat"><small>데이터 원본</small><b>VPS + GitHub</b><span>읽기 전용 수집</span></div>`; }
function renderCards(filter='all') { let visible = services.filter(s => filter === 'all' || (filter === 'attention' ? ['down','degraded','unknown'].includes(s.automated_status) : s.lifecycle === filter)); $('#service-count').textContent = `${visible.length}개 표시`; $('#services').innerHTML = visible.map(s => `<article class="card"><div class="card-head"><div><span class="service-name">${esc(s.name)}</span><p>${esc(s.description)}</p></div><span class="pill ${statusClass(s.automated_status)}" aria-label="상태: ${esc(statusText[s.automated_status] || s.automated_status)}">● ${esc(statusText[s.automated_status] || s.automated_status)}</span></div><div class="meta"><div><small>점검</small><span>${checkSummary(s)}</span></div><div><small>최근 GitHub</small><span>${esc(s.github?.latest_commit?.message || '기록 없음')}</span></div></div><div class="card-foot"><span>다음: ${esc(s.next_action || '미정')}</span>${s.public_url ? `<a href="${esc(s.public_url)}" target="_blank" rel="noreferrer">서비스 ↗</a>` : ''}</div></article>`).join('') || '<div class="empty">해당 조건의 서비스가 없습니다.</div>'; }
function renderLists() { const updates = services.filter(s => s.github?.latest_commit).sort((a,b) => String(b.github.latest_commit.date).localeCompare(String(a.github.latest_commit.date))); $('#updates').innerHTML = updates.map(s => `<div class="list-item"><b>${esc(s.name)}</b><span>${esc(s.github.latest_commit.message)}</span><small>${fmtDate(s.github.latest_commit.date)}</small></div>`).join('') || '<div class="empty">업데이트 기록 없음</div>'; $('#next-actions').innerHTML = services.map(s => `<div class="list-item"><b>${esc(s.name)}</b><span>${esc(s.next_action || '미정')}</span></div>`).join(''); $('#attention').innerHTML = services.filter(s => ['down','degraded','unknown'].includes(s.automated_status)).map(s => `<div class="list-item"><b>${esc(s.name)}</b><span>${esc(statusText[s.automated_status])}: ${checkSummary(s)}</span></div>`).join('') || '<div class="healthy">● 현재 자동 확인 항목 없음</div>'; }
function renderLists() { const updates = services.filter(s => s.github?.latest_commit).sort((a,b) => String(b.github.latest_commit.date).localeCompare(String(a.github.latest_commit.date))); $('#updates').innerHTML = updates.map(s => `<div class="list-item"><b>${esc(s.name)}</b><span>${esc(s.github.latest_commit.message)}</span><small>${fmtDate(s.github.latest_commit.date)}</small></div>`).join('') || '<div class="empty">업데이트 기록 없음</div>'; $('#ideas').innerHTML = ideas.map(i => `<div class="list-item"><b>${esc(i.title)}</b><span>${esc(i.service_name || '전체 서비스')} · ${esc(i.status || '아이디어')} · 우선순위 ${esc(i.priority || '미정')}</span><small>${i.target_date ? `목표일 ${esc(i.target_date)}` : '목표일 미정'}</small></div>`).join('') || '<div class="empty">등록된 아이디어·계획 없음</div>'; $('#next-actions').innerHTML = services.map(s => `<div class="list-item"><b>${esc(s.name)}</b><span>${esc(s.next_action || '미정')}</span></div>`).join(''); $('#attention').innerHTML = services.filter(s => ['down','degraded','unknown'].includes(s.automated_status)).map(s => `<div class="list-item"><b>${esc(s.name)}</b><span>${esc(statusText[s.automated_status])}: ${checkSummary(s)}</span></div>`).join('') || '<div class="healthy">● 현재 자동 확인 항목 없음</div>'; }
function showView(view) { activeView = view; document.querySelectorAll('.view').forEach(section => { section.hidden = section.id !== `${view}-view`; }); document.querySelectorAll('.view-tab').forEach(button => { const selected = button.dataset.view === view; button.classList.toggle('active', selected); button.setAttribute('aria-pressed', selected ? 'true' : 'false'); }); }
function renderAnalytics() { if (ga4.status !== 'ok') { $('#analytics').innerHTML = `<div class="empty">${ga4.status === 'error' ? 'GA4 수집 실패' : 'GA4 연결 대기'}</div>`; return; } const metrics = ga4.metrics || {}; const metric = (label, key) => `<div class="list-item"><b>${label}</b><span>${Number(metrics[key] || 0).toLocaleString('ko-KR')}</span></div>`; const pages = (Array.isArray(ga4.top_pages) ? ga4.top_pages : []).map(i => `${esc(i.label)} ${Number(i.value).toLocaleString('ko-KR')}`).join(' · ') || '기록 없음'; const channels = (Array.isArray(ga4.traffic_channels) ? ga4.traffic_channels : []).map(i => `${esc(i.label)} ${Number(i.value).toLocaleString('ko-KR')}`).join(' · ') || '기록 없음'; $('#analytics').innerHTML = `${metric('사용자', 'activeUsers')}${metric('세션', 'sessions')}${metric('조회수', 'screenPageViews')}${metric('참여 세션', 'engagedSessions')}<div class="list-item"><b>상위 페이지</b><span>${pages}</span></div><div class="list-item"><b>유입 채널</b><span>${channels}</span></div>`; }
function renderRules() { if (!rulesDocument) return; const query = $('#rules-search').value.trim().toLocaleLowerCase('ko-KR'), source = $('#rules-source').value, group = $('#rules-group').value, scope = $('#rules-scope').value; const all = rulesDocument.entries; const entries = all.filter(e => (source==='all'||e.source===source) && (group==='all'||e.group_id===group) && (scope==='all'||(e.scopes||[]).includes(scope)) && String(e.text).toLocaleLowerCase('ko-KR').includes(query)); $('#rules-count').textContent=`${entries.length}개 표시 · 전체 ${all.length}개 기록`; $('#rules-group-summary').innerHTML=Object.entries(ruleGroups).map(([id,label])=>`<button type="button" class="rule-group-chip" data-rules-group="${id}">${esc(label)} <b>${all.filter(e=>e.group_id===id).length}</b></button>`).join(''); $('#rules-items').innerHTML=entries.map(e=>`<article class="rule-item"><div class="rule-source">${esc(ruleGroups[e.group_id]||e.group_id)} · ${esc(e.source)} · 항목 ${esc(e.source_order)}</div><div class="rule-scopes">${(e.scopes||[]).map(s=>`<span>${esc(ruleScopes[s]||s)}</span>`).join('')}</div><p>${esc(e.text)}</p></article>`).join('')||'<div class="empty">일치하는 기록이 없습니다.</div>'; }
async function loadRules() { try { const response = await fetch('../rules-fixture.json', {cache:'no-store'}); if (!response.ok) throw new Error(`fixture ${response.status}`); const data = await response.json(); if (!Array.isArray(data.entries)) throw new Error('잘못된 샘플 데이터'); rulesDocument = data; $('#rules-updated').textContent = '공개 샘플 · 실제 기록 없음'; renderRules(); } catch (error) { rulesDocument = null; $('#rules-updated').textContent = '샘플을 불러오지 못했습니다'; $('#rules-count').textContent = ''; $('#rules-items').textContent = `샘플을 불러오지 못했습니다: ${error.message}`; } }
async function start() { try { const response = await fetch('../snapshot.json', {cache:'no-store'}); if (!response.ok) throw new Error(`snapshot ${response.status}`); const data = await response.json(); services = data.services || []; ideas = data.ideas || []; ga4 = data.ga4 || {status:'not_configured'}; $('#collected').textContent = `마지막 수집 ${fmtDate(data.collected_at)} · 5분마다 갱신`; renderSummary(); renderCards(activeFilter); renderAnalytics(); renderLists(); } catch (error) { $('#collected').textContent = '수집 결과 없음'; $('#services').innerHTML = `<div class="error" role="alert">운영 상태를 불러오지 못했습니다. 수집기 로그를 확인해 주세요.</div>`; console.error(error); } }
document.querySelectorAll('.filter').forEach(b => b.addEventListener('click', () => { activeFilter = b.dataset.filter; document.querySelectorAll('.filter').forEach(x => { x.classList.toggle('active', x === b); x.setAttribute('aria-pressed', x === b ? 'true' : 'false'); }); renderCards(activeFilter); }));
document.querySelectorAll('.view-tab').forEach(button => button.addEventListener('click', () => { showView(button.dataset.view); if (activeView === 'rules') void loadRules(); }));
$('#rules-search').addEventListener('input', renderRules);
$('#rules-source').addEventListener('change', renderRules);
$('#rules-group').addEventListener('change', renderRules);
$('#rules-scope').addEventListener('change', renderRules);
showView(activeView);
$('#refresh').addEventListener('click', async () => { $('#refresh').disabled = true; await start(); $('#refresh').disabled = false; });
refreshTimer = window.setInterval(start, 300000);
start();
